Практическая работа по спринту 7
Alex009/architecture-sprint-7 pull request #1
Opened 2024-11-13 17:56 UTC by Alex009

2024-11-21 17:48 UTC, kostya05983 requested changes

2024-11-21 17:48 UTC, kostya05983 commented on Exc5/non-admin-api-allow.yml
> +  - from:
а как же в обратную сторону to?

2024-11-21 17:48 UTC, kostya05983 commented on Exc5/non-admin-api-allow.yml
> +  - from:
"Таким образом, сетевые политики должны разрешить сетевой трафик в обе стороны"

2024-11-24 14:55 UTC, Alex009 commented on Exc5/non-admin-api-allow.yml
> +  - from:
добавил и обратное ограничение

2024-11-26 07:48 UTC, merged